### ISSUE TITLE
Problems with Codeblock Style Docs

### ISSUE THREAD

**Issue by gapplef** [next-theme/theme-next-docs#15]
Please follow this Issue template to provide relevant information, such as source code repository, website URL and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、网站链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/next-theme/hexo-theme-next/releases/latest) version of NexT.
- [x] I have already read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.js.org/docs/).
- [x] I have already searched for current [issues](https://github.com/next-theme/hexo-theme-next/issues), which does not help me.

***

1. According to the [docs](https://theme-next.js.org/docs/theme-settings/miscellaneous.html#Codeblock-Style), the default highlight style is `tomorrow`, but in reality, the default style is `default`, which I believe is different from `tomorrow`. I don't know whether this is a bug, or just the docs is outdated.

2. Also, the docs of code block style didn't mention that user should turn on/off highlight/prism in `Hexo` _config.yml, and I only get this information in the [preview](https://theme-next.js.org/highlight/) page. I think this may be a bit confusing for new use.

**Comment by stevenjoezhang** [comment]
1. The documentation gives typical allowable values, not default values. For example, pjax is disabled by default (`pjax: false`), but the example given in the document is `pjax: true` (https://theme-next.js.org/docs/third-party-services/external-libraries.html#PJAX). This is just to inform the user that `true` is a legal parameter.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/theme-next-docs/commit/30eba96040d948678c458dbcbd52dcc1a9f20586

**Comment by gapplef** [comment]
I mean this:
![Screenshot](https://user-images.githubusercontent.com/5604665/92253753-7c251700-ef02-11ea-8389-90d620ded094.png)

Actually, the default codestyle is `tomorrow`, previously, but it changes to `default` in the latest version.
I wonder if this change is made by mistake?

**Comment by stevenjoezhang** [comment]
I'm not sure how to answer your question, because highlight.js has the same color scheme as the tomorrow theme, but the name is different. Maybe you can checkout this commit to find the answer: https://github.com/next-theme/hexo-theme-next/commit/9fdaba295a2c6c707a7d96d331762ab571b89c1a

**Comment by gapplef** [comment]
Problem is the style `default` of highlight.js  is not `tomorrow`!

After updated to the latest version of `next` theme, I noticed the highlight style changed.
I went to see the docs and got more confused by the claim that "_default style is `tomorrow`_".
Things back to normal until I add the following setting to my `_config.next.yml`:
```yml
codeblock:
  # Code Highlight theme
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: tomorrow
    dark: tomorrow-night
```
