### ISSUE TITLE
the confusion about hexo-generator-searchdb options 

### ISSUE THREAD

**Issue by ousugo** [next-theme/theme-next-docs#16]
According to the [docs](https://www.npmjs.com/package/hexo-generator-searchdb#options) of hexo-generator-searchdb in npm, the four arguments are [path, field, content, format]
![image](https://user-images.githubusercontent.com/43401755/92195061-af35bf00-ee9e-11ea-8aa9-e6d6dec49f29.png)

But in the [Next docs ](https://theme-next.js.org/docs/third-party-services/search-services.html#Local-Search), the four arguments are [path, field, format, limit]
![image](https://user-images.githubusercontent.com/43401755/92195240-06d42a80-ee9f-11ea-9633-c82d365de41c.png)

Which one is the right?

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/theme-next-docs/commit/30eba96040d948678c458dbcbd52dcc1a9f20586
