### ISSUE TITLE
Docs里关于Math Equations的every_page参数设置说明有误

### ISSUE THREAD

**Issue by PiggerZZM** [next-theme/theme-next-docs#24]
Please follow this Issue template to provide relevant information, such as source code repository, website URL and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、网站链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using NexT version 8.0 or later.
- [ ] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Troubleshooting page of NexT](https://theme-next.js.org/docs/troubleshooting.html).
- [ ] I have already searched for current [issues](https://github.com/next-theme/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
设置`every_page = true`对每篇文章的数学公式进行渲染 

## Actual behavior 
与文档里的说明不符
https://theme-next.js.org/docs/third-party-services/math-equations.html
![捕获](https://user-images.githubusercontent.com/21277183/98317193-05e28500-2017-11eb-8d42-d8fd8299c669.PNG)

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/theme-next-docs/commit/2af1759c3f42eafb3e8bc2e742f0df1ba24c6cb7
