### ISSUE TITLE
Typo under getting-started/configuration

### ISSUE THREAD

**Issue by v1siuol** [next-theme/theme-next-docs#40]
Under https://github.com/next-theme/theme-next-docs/blob/a6f37a29363e2868a78b71902936bdfe908152eb/source/docs/getting-started/configuration.md#usage, `cp theme/next/_config.yml _config.next.yml` should be `cp themes/next/_config.yml _config.next.yml`.

Since many users might visit this section for config instructions, this typo might be misleading to some extent.

**Comment by stevenjoezhang** [comment]
Thanks for your feedback. Fixed in 43b59faec259b791cb5cdbc735f17e2c662e37f8
