### ISSUE TITLE
Can't close chat sidebar 

### ISSUE THREAD

**Issue by No5972** [next-theme/theme-next-docs#54]
**Well, it can be closed once I scroll down but it is still suggested to adjust it.**

The GitHub corner mark blocked the close button of the chat sidebar and I can't close this chat sidebar... 🤣

![](https://img-blog.csdnimg.cn/90d1510555cb471786b7215ec33aa2df.png)

**Comment by stevenjoezhang** [comment]
Thanks for your feedback, I have reduced the value of z-index 😜 https://github.com/next-theme/hexo-theme-next/commit/6067b5f145810643e805c10ead57e3980804d9fb
