### ISSUE TITLE
maybe a doc issue

### ISSUE THREAD

**Issue by xdlrt** [next-theme/theme-next-docs#59]
source/docs/theme-settings/index.md

this doc shows _config.yml everywhere, but I tried and I found that I should use _config.next.yml.

hexo 6.0.0
next 8.9.0

**Comment by stevenjoezhang** [comment]
Thanks for your feedback. I'll replace `_config.yml` with "Hexo / NexT Config File" later. Theme Config File includes `themes/next/_config.yml`, `node_modules/hexo-theme-next/_config.yml` and `_config.next.yml`.

**Comment by xdlrt** [comment]
thanks for reply.😄  hope this will be fixed sooner.

**Comment by stevenjoezhang** [comment]
Docs updated: https://github.com/next-theme/theme-next-docs/commit/82d15eb3b2e3206999a1b41bd49716c0195695e3
