### ISSUE TITLE
images' size

### ISSUE THREAD

**Issue by pylover7** [next-theme/theme-next-docs#7]
Is there a limit to the size of the uploaded image?

**Comment by stevenjoezhang** [comment]
I don't quite understand your question. Are you referring to the limit of GitHub?

**Comment by pylover7** [comment]
> I don't quite understand your question. Are you referring to the limit of GitHub?
Yeah

**Comment by stevenjoezhang** [comment]
According to GitHub documentation,
> To keep your repository size manageable and prevent performance issues, you can configure a file size limit for repositories on your instance.

> By default, when you enforce repository upload limits, people cannot add or update files larger than 100 MB.

https://docs.github.com/en/enterprise/2.17/admin/installation/setting-git-push-limits

**Comment by pylover7** [comment]
@stevenjoezhang Thanks for your anwser~

**Comment by stevenjoezhang** [comment]
You're welcome :)
